name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: mkdir build && cd build
    - name: Configure
      run: cmake ..
    - name: Build
      run: make 

